package com.github.k1mb1.vkr_backend.domain.lessons.requests;

import com.github.k1mb1.vkr_backend.domain.lessons.LessonType;
import jakarta.validation.constraints.AssertTrue;
import jakarta.validation.constraints.NotNull;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * A single slot inside a {@link LessonScheduleEntry}.
 *
 * <p>One slot = one concrete lesson occurrence at an exact date and time.
 * For WEEKLY recurrence the {@code date} is the date of the first occurrence;
 * subsequent occurrences are generated by the scheduling algorithm by adding
 * {@code intervalWeeks} weeks to this date.
 * For ONCE recurrence the {@code date} is the only occurrence.
 *
 * <p>Rules:
 * <ul>
 *   <li>{@code date} – exact start date and time of the (first) occurrence.</li>
 *   <li>{@code groupId} – must be {@code null} for {@link LessonType#LECTURE}
 *       because lectures always target the whole enrolled cohort.</li>
 * </ul>
 */
public record LessonSlot(
    @NotNull LessonType type,
    @NotNull OffsetDateTime date,
    UUID groupId
) {
    /** Lectures are whole-cohort — {@code groupId} must not be set. */
    @AssertTrue(message = "groupId must be null for LECTURE slots")
    public boolean isGroupIdNullForLecture() {
        return type != LessonType.LECTURE || groupId == null;
    }
}
