server:
  port: ${PORT:8081}

spring:
  application:
    name: vkr-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        default_batch_fetch_size: 30
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURSESERVER_ISSUER_URI}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
