spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        cache:
          use_second_level_cache: false
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    com.github.k1mb1.vkr_backend: INFO

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
