spring:
  application:
    name: vkr-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true