--liquibase formatted sql
--changeset k1mb1:20260427091500-remove-lesson-archiving

-- Remove archived columns from LESSONS
ALTER TABLE LESSONS
DROP COLUMN ARCHIVED_AT;

ALTER TABLE LESSONS
DROP COLUMN ARCHIVED;

--rollback ALTER TABLE LESSONS ADD COLUMN ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;
--rollback ALTER TABLE LESSONS ADD COLUMN ARCHIVED_AT TIMESTAMPTZ;
