--liquibase formatted sql
--changeset k1mb1:20260324172624-add-archiving

-- SUBJECTS
ALTER TABLE SUBJECTS
ADD COLUMN ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE SUBJECTS
ADD COLUMN ARCHIVED_AT TIMESTAMPTZ;

-- LESSONS
ALTER TABLE LESSONS
ADD COLUMN ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE LESSONS
ADD COLUMN ARCHIVED_AT TIMESTAMPTZ;

--rollback ALTER TABLE LESSONS DROP COLUMN ARCHIVED_AT;
--rollback ALTER TABLE LESSONS DROP COLUMN ARCHIVED;

--rollback ALTER TABLE SUBJECTS DROP COLUMN ARCHIVED_AT;
--rollback ALTER TABLE SUBJECTS DROP COLUMN ARCHIVED;