--liquibase formatted sql
--changeset k1mb1:20260418130000-add-not-null-core-columns

ALTER TABLE STUDENTS
    ALTER COLUMN USERNAME SET NOT NULL;

ALTER TABLE LESSONS
    ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE SUBJECTS
    ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE STUDENT_GROUPS
    ALTER COLUMN NAME SET NOT NULL;

--rollback ALTER TABLE STUDENT_GROUPS ALTER COLUMN NAME DROP NOT NULL;
--rollback ALTER TABLE SUBJECTS ALTER COLUMN NAME DROP NOT NULL;
--rollback ALTER TABLE LESSONS ALTER COLUMN NAME DROP NOT NULL;
--rollback ALTER TABLE STUDENTS ALTER COLUMN USERNAME DROP NOT NULL;
