--liquibase formatted sql
--changeset k1mb1:20260217-initial-tables
CREATE TYPE LESSON_TYPE AS ENUM ('NONE','LECTURE','PRACTICE');
CREATE TYPE PRESENCE_TYPE AS ENUM ('NONE','PRESENT','NOT_PRESENT');

CREATE TABLE STUDENT_GROUPS
(
    ID         UUID        NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    NAME       VARCHAR(255)
);

CREATE TABLE STUDENTS
(
    ID         UUID        NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    USERNAME   VARCHAR(255),
    GROUP_ID   UUID,
    CONSTRAINT FK_STUDENTS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES STUDENT_GROUPS (ID) ON DELETE CASCADE
);

CREATE TABLE SUBJECTS
(
    ID          UUID        NOT NULL PRIMARY KEY,
    CREATED_AT  TIMESTAMPTZ NOT NULL,
    UPDATED_AT  TIMESTAMPTZ NOT NULL,
    NAME        VARCHAR(255),
    DESCRIPTION TEXT
);

CREATE TABLE LESSONS
(
    ID         UUID        NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    DATE_TIME  TIMESTAMPTZ,
    TYPE       LESSON_TYPE NOT NULL DEFAULT 'NONE',
    SUBJECT_ID UUID        NOT NULL,
    NAME       VARCHAR(255),
    CONSTRAINT FK_LESSONS_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID) ON DELETE CASCADE
);

CREATE TABLE TEACHERS
(
    ID         UUID                NOT NULL PRIMARY KEY,
    USERNAME   VARCHAR(255) UNIQUE NOT NULL,
    EMAIL      VARCHAR(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMPTZ         NOT NULL,
    UPDATED_AT TIMESTAMPTZ         NOT NULL
);

CREATE TABLE SUBJECT_STUDENT
(
    SUBJECT_ID UUID NOT NULL,
    STUDENT_ID UUID NOT NULL,
    PRIMARY KEY (SUBJECT_ID, STUDENT_ID),
    CONSTRAINT FK_SUBJECT_STUDENT_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUBJECT_STUDENT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID) ON DELETE CASCADE
);

CREATE TABLE SUBJECT_TEACHER
(
    SUBJECT_ID UUID NOT NULL,
    TEACHER_ID UUID NOT NULL,
    PRIMARY KEY (SUBJECT_ID, TEACHER_ID),
    CONSTRAINT FK_SUBJECT_TEACHER_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUBJECT_TEACHER_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID) ON DELETE CASCADE
);

CREATE TABLE STUDENT_ATTENDANCES
(
    ID         UUID          NOT NULL PRIMARY KEY,
    NOTE       VARCHAR(255),
    PRESENCE   PRESENCE_TYPE NOT NULL DEFAULT 'NONE',
    LESSON_ID  UUID          NOT NULL,
    STUDENT_ID UUID          NOT NULL,
    CREATED_AT TIMESTAMPTZ   NOT NULL,
    UPDATED_AT TIMESTAMPTZ   NOT NULL,
    CONSTRAINT FK_STUDENT_ATTENDANCES_LESSON FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_STUDENT_ATTENDANCES_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID) ON DELETE CASCADE,
    CONSTRAINT UK_ATTENDANCE_LESSON_STUDENT UNIQUE (LESSON_ID, STUDENT_ID)
);

CREATE TABLE STUDENT_GRADES
(
    ID         UUID        NOT NULL PRIMARY KEY,
    COMMENT    VARCHAR(255),
    VALUE      INTEGER,
    LESSON_ID  UUID        NOT NULL,
    STUDENT_ID UUID        NOT NULL,
    CREATED_AT TIMESTAMPTZ NOT NULL,
    UPDATED_AT TIMESTAMPTZ NOT NULL,
    CONSTRAINT FK_STUDENT_GRADES_LESSON FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_STUDENT_GRADES_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID) ON DELETE CASCADE,
    CONSTRAINT UK_GRADE_LESSON_STUDENT UNIQUE (LESSON_ID, STUDENT_ID)
);

CREATE INDEX IX_STUDENTS_GROUP_ID ON STUDENTS (GROUP_ID);
CREATE INDEX IX_LESSONS_SUBJECT_ID ON LESSONS (SUBJECT_ID);
CREATE INDEX IX_LESSONS_TYPE ON LESSONS (TYPE);
CREATE INDEX IX_STUDENT_ATTENDANCES_LESSON_ID ON STUDENT_ATTENDANCES (LESSON_ID);
CREATE INDEX IX_STUDENT_ATTENDANCES_STUDENT_ID ON STUDENT_ATTENDANCES (STUDENT_ID);
CREATE INDEX IX_STUDENT_ATTENDANCES_PRESENCE ON STUDENT_ATTENDANCES (PRESENCE);
CREATE INDEX IX_STUDENT_GRADES_LESSON_ID ON STUDENT_GRADES (LESSON_ID);
CREATE INDEX IX_STUDENT_GRADES_STUDENT_ID ON STUDENT_GRADES (STUDENT_ID);


--rollback DROP INDEX IF EXISTS ix_student_grades_student_id;
--rollback DROP INDEX IF EXISTS ix_student_grades_lesson_id;
--rollback DROP INDEX IF EXISTS ix_student_attendances_presence;
--rollback DROP INDEX IF EXISTS ix_student_attendances_student_id;
--rollback DROP INDEX IF EXISTS ix_student_attendances_lesson_id;
--rollback DROP INDEX IF EXISTS ix_lessons_type;
--rollback DROP INDEX IF EXISTS ix_lessons_subject_id;
--rollback DROP INDEX IF EXISTS ix_students_group_id;
--rollback DROP TABLE IF EXISTS student_grades;
--rollback DROP TABLE IF EXISTS student_attendances;
--rollback DROP TABLE IF EXISTS subject_teacher;
--rollback DROP TABLE IF EXISTS subject_student;
--rollback DROP TABLE IF EXISTS teachers;
--rollback DROP TABLE IF EXISTS lessons;
--rollback DROP TABLE IF EXISTS subjects;
--rollback DROP TABLE IF EXISTS students;
--rollback DROP TABLE IF EXISTS student_groups;
--rollback DROP TYPE IF EXISTS presence_type;
--rollback DROP TYPE IF EXISTS lesson_type;