--liquibase formatted sql
--changeset k1mb1:20260328-add-subgroups

-- Allow student_groups to be subgroups of another group.
-- parent_group_id = NULL  → main group  (e.g. ИСТ-21)
-- parent_group_id = <id>  → subgroup    (e.g. ИСТ-21/1, ИСТ-21/2)
ALTER TABLE STUDENT_GROUPS
    ADD COLUMN PARENT_GROUP_ID UUID,
    ADD CONSTRAINT FK_STUDENT_GROUPS_PARENT
        FOREIGN KEY (PARENT_GROUP_ID) REFERENCES STUDENT_GROUPS (ID) ON DELETE CASCADE;

-- A lesson can now be targeted at a specific group or subgroup.
-- NULL means the lesson is for every student enrolled in the subject (no group filter).
ALTER TABLE LESSONS
    ADD COLUMN GROUP_ID UUID,
    ADD CONSTRAINT FK_LESSONS_GROUP
        FOREIGN KEY (GROUP_ID) REFERENCES STUDENT_GROUPS (ID) ON DELETE SET NULL;

CREATE INDEX IX_STUDENT_GROUPS_PARENT_GROUP_ID ON STUDENT_GROUPS (PARENT_GROUP_ID);
CREATE INDEX IX_LESSONS_GROUP_ID ON LESSONS (GROUP_ID);

--rollback DROP INDEX IF EXISTS IX_LESSONS_GROUP_ID;
--rollback DROP INDEX IF EXISTS IX_STUDENT_GROUPS_PARENT_GROUP_ID;
--rollback ALTER TABLE LESSONS DROP CONSTRAINT IF EXISTS FK_LESSONS_GROUP;
--rollback ALTER TABLE LESSONS DROP COLUMN IF EXISTS GROUP_ID;
--rollback ALTER TABLE STUDENT_GROUPS DROP CONSTRAINT IF EXISTS FK_STUDENT_GROUPS_PARENT;
--rollback ALTER TABLE STUDENT_GROUPS DROP COLUMN IF EXISTS PARENT_GROUP_ID;
